More silent operation, reopen on branch

diff --git a/git-ghbranch b/git-ghbranch
--- a/git-ghbranch
+++ b/git-ghbranch
@@ -11,12 +11,12 @@ BRANCH_NAME=$1
 sanity_checks
 
 # Assign to user
-echo "Assigning issue to $GITHUB_USER"
-$CURL_CMD "$AUTH" -X PATCH --data-binary "{\"assignee\": \"$GITHUB_USER\"}" "$ISSUE_URL" || fail "Failed to assign issue"
+echo "Assigning issue to $GITHUB_USER and opening it"
+$CURL_CMD "$AUTH" -X PATCH --data-binary "{\"assignee\": \"$GITHUB_USER\", \"state\": \"open\"}" "$ISSUE_URL"  > /dev/null || fail "Failed to assign issue"
 
 # Add tag
 echo "Marking #$BRANCH_NAME as $PROGRESS_LABEL"
-$CURL_CMD "$AUTH" -X POST --data-binary "[\"$PROGRESS_LABEL\"]" "$ISSUE_URL/labels" || fail "Failed to mark as $PROGRESS_LABEL"
+$CURL_CMD "$AUTH" -X POST --data-binary "[\"$PROGRESS_LABEL\"]" "$ISSUE_URL/labels"  > /dev/null || fail "Failed to mark as $PROGRESS_LABEL"
 
 # Cache the jira issue title for later cheaper commits
 echo "Getting description for #$BRANCH_NAME"
diff --git a/git-ghfix b/git-ghfix
--- a/git-ghfix
+++ b/git-ghfix
@@ -20,10 +20,10 @@ git checkout master
 git merge $BRANCH_NAME
 
 echo "Closing issue #$BRANCH_NAME"
-$CURL_CMD "$AUTH" -X PATCH --data-binary "{\"state\": \"closed\"}" "$ISSUE_URL" || fail "Failed to close issue"
+$CURL_CMD "$AUTH" -X PATCH --data-binary "{\"state\": \"closed\"}" "$ISSUE_URL" > /dev/null || fail "Failed to close issue"
 
 echo "Removing $PROGRESS_LABEL label"
-$CURL_CMD "$AUTH" -X DELETE "$ISSUE_URL/labels/$PROGRESS_LABEL" || fail "Failed to remove $PROGRESS_LABEL label"
+$CURL_CMD "$AUTH" -X DELETE "$ISSUE_URL/labels/$PROGRESS_LABEL" > /dev/null  || fail "Failed to remove $PROGRESS_LABEL label"
 
 echo "*** You are now on branch master ***"
 
